# DO NOT CHANGE the "init" and "install" sections below
# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

environment:
  BIOC_USE_DEVEL: FALSE
  GCC_PATH: mingw_32
  matrix:
    - R_VERSION: release
      BIOC_USE_DEVEL: TRUE
      
    - R_VERSION: release
      BIOC_USE_DEVEL: TRUE
      GCC_PATH: mingw_64
      R_ARCH: x64
      
#    - R_VERSION: release
#    - R_VERSION: 3.4.4
#    - R_VERSION: 3.4.2
#    - R_VERSION: 3.4.0
      
build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_bioc BiocCheck roxygen2 GenomeInfoDbData
  - R -e "devtools::install(upgrade_dependencies=TRUE, dependencies=TRUE)"
  
test_script:
  - R -e "date(); devtools::check(build_args='--no-build-vignettes', manual=FALSE, args='--no-build-vignettes')"
  - R -e "date(); devtools::test()"
  - R -e "date(); devtools::run_examples(show=FALSE)"
  - R -e "date(); BiocCheck::BiocCheck()"
  - R -e "date(); devtools::build_vignettes(); date()"

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
