# 
# Use the Bootstrap code from the rwinlib project for CRAN 
# https://github.com/rwinlib
#
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest https://raw.githubusercontent.com/rwinlib/base/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  # install ImageMagick and set path correctly at first position
  # only needed for building the vignette
  #- ps: InstallMiktex
  #- choco install -y -PackageParameters LegacySupport=true imagemagick
  #- set "PATH=C:\Program Files\ImageMagick-7.0.8-Q16;%PATH%"

cache:
  - C:\RLibrary

environment:
  # parameters to setup R environment
  # https://github.com/krlmlr/r-appveyor/blob/master/README.md
  PKGTYPE: win.binary
  BIOC_USE_DEVEL: FALSE
  USE_RTOOLS: TRUE
  KEEP_VIGNETTES: TRUE
  GCC_PATH: mingw_64
  R_ARCH: x64
  APPVEYOR_SAVE_CACHE_ON_ERROR: TRUE
  
  matrix:
    - R_VERSION: devel
      BIOC_USE_DEVEL: TRUE
#    - R_VERSION: devel
#      BIOC_USE_DEVEL: TRUE
#      GCC_PATH: mingw_32
#      R_ARCH: i386    
    - R_VERSION: release
    - R_VERSION: 3.6.0
      
build_script:
  - travis-tool.sh install_bioc rlang S4Vectors
  - Rscript setupEnv.R

test_script:
    - R CMD build --no-build-vignettes .
    - R CMD check --install-args=--build --no-vignettes --no-manual --timings *tar.gz
    - R -e "BiocCheck::BiocCheck(list.files(path='.', pattern='.tar.gz'))"
    - R -e "devtools::run_examples(document=FALSE)"
    # runs currently into an error saying: "LaTeX Error: Missing \begin{document}."
    #    - cd vignettes && R CMD Sweave --engine=knitr::knitr --pdf OUTRIDER.Rnw

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - appveyor PushArtifact \*_*.tar.gz
  - appveyor PushArtifact \*_*.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
